# Generated by Django 3.0.5 on 2020-05-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(null=True, upload_to='blog/', verbose_name='Изображение (530 x 210)'),
        ),
    ]
