# Generated by Django 3.0.5 on 2020-05-03 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('image', models.ImageField(null=True, upload_to='portfoliio/', verbose_name='Изображение (432 x 432)')),
                ('description', models.CharField(max_length=255, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioItemImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_2000', models.ImageField(null=True, upload_to='portfoliio/', verbose_name='Изображение (2200)')),
                ('image_1000', models.ImageField(null=True, upload_to='portfoliio/', verbose_name='Изображение (1100)')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.PortfolioItem', verbose_name='Элемент портфолио')),
            ],
        ),
    ]
