# Generated by Django 3.0.5 on 2020-05-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название партнера')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Название партнера')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Название партнера')),
                ('name_az', models.CharField(max_length=255, null=True, verbose_name='Название партнера')),
                ('image', models.ImageField(null=True, upload_to='partner/', verbose_name='Лого (136 x ??)')),
                ('description', models.CharField(max_length=255, null=True, verbose_name='Описание')),
                ('description_en', models.CharField(max_length=255, null=True, verbose_name='Описание')),
                ('description_ru', models.CharField(max_length=255, null=True, verbose_name='Описание')),
                ('description_az', models.CharField(max_length=255, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Совместная работа')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Совместная работа')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Совместная работа')),
                ('name_az', models.CharField(max_length=255, null=True, verbose_name='Совместная работа')),
                ('price_item', models.ManyToManyField(related_name='units', to='partner.Partner', verbose_name='Относится к партнеру')),
            ],
            options={
                'verbose_name': 'Совместная работа',
                'verbose_name_plural': 'Совместные работы',
            },
        ),
    ]
