# Generated by Django 3.0.5 on 2020-05-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='description_az',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='partner',
            name='description_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='partner',
            name='description_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='partner',
            name='name_az',
            field=models.CharField(max_length=255, null=True, verbose_name='Название партнера'),
        ),
        migrations.AddField(
            model_name='partner',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название партнера'),
        ),
        migrations.AddField(
            model_name='partner',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название партнера'),
        ),
        migrations.AddField(
            model_name='unit',
            name='name_az',
            field=models.CharField(max_length=255, null=True, verbose_name='Совместная работа'),
        ),
        migrations.AddField(
            model_name='unit',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Совместная работа'),
        ),
        migrations.AddField(
            model_name='unit',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Совместная работа'),
        ),
    ]
